### ISSUE TITLE
Title not redirecting to blog

### ISSUE THREAD

**Issue by Sumith1896** [sympy/planet-sympy#44]
@kshitij10496 Your have not setup your config correctly, could you fix this line https://github.com/kshitij10496/kshitij10496.github.io/blob/b314d0c3c68842e5776e54593cc15fda7ef26902/_config.yml#L11
Cheers!

**Comment by kshitij10496** [comment]
Hey @Sumith1896 
Thanks for pointing out the issue.
Its fixed now. :smile:
