### ISSUE TITLE
Page build failure

### ISSUE THREAD

**Issue by certik** [sympy/planet-sympy#62]
I've been getting quite a few of "[planet-sympy/planet.sympy.org] Page build failure" emails from GitHub. Here is how the email looks like:
```
The page build failed for the `gh-pages` branch with the following error:

unable to build page. Please try again later.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```
It doesn't provide any other information. Here are the dates/times of the 11 most recent emails:
```
Tue, Apr 4, 2017 at 8:42 AM
Tue, May 2, 2017 at 6:32 PM
Tue, May 2, 2017 at 7:13 PM
Wed, May 10, 2017 at 8:22 AM
Wed, May 31, 2017 at 7:11 AM
Thu, Jun 1, 2017 at 4:32 PM
Thu, Jun 1, 2017 at 11:52 PM
Fri, Jun 2, 2017 at 6:33 AM
Fri, Jun 2, 2017 at 9:18 AM
Sun, Jun 4, 2017 at 8:52 PM
Mon, Jun 5, 2017 at 3:52 AM
```
I don't know what is going on or what can be causing this, but it seems that besides these failures things work.

**Comment by asmeurer** [comment]
We don't seem to have a .nojekyll file, so probably Jekyll is trying to build it.

**Comment by certik** [comment]
I thought we had it, but I don't see it there now: https://github.com/planet-sympy/planet.sympy.org/tree/3b5fa0dffdb0b1c6d0d70bbd2d7d10adc0c55066

**Comment by asmeurer** [comment]
Because your deploy script [wipes](https://github.com/sympy/planet-sympy/blob/d463702b3afe354e3b835f9014ca6bff4db6a2d9/update.sh#L29) everything. If we could use doctr it would be smarter than this. Might be worth spending some time getting it to work on [GitLab](https://github.com/drdoctr/doctr/issues/189).

**Comment by asmeurer** [comment]
For now, let's just add a `touch .nojekyll` to the deploy script.

**Comment by certik** [comment]
Thanks, let's see if it's fixed now.

I created #64 for the `doctr` thing.
