### ISSUE TITLE
Planet sympy not updating

### ISSUE THREAD

**Issue by asmeurer** [sympy/planet-sympy#66]
See https://github.com/planet-sympy/planet.sympy.org/commits/gh-pages. It hasn't updated in 11 days.

**Comment by certik** [comment]
Got it. I am triggering the pipeline from a cron every 20 min, and it has been returning:
```
{"message":{"base":["Insufficient permissions to create a new pipeline"]}}
```
I am looking into it, probably some permissions must have changed at gitlab.com.

**Comment by certik** [comment]
It's fixed, I just had to regenerate the TOKEN, as the new GitLab release changed some permissions.
