### ISSUE TITLE
[GSoC] Blog link needs to be re-updated

### ISSUE THREAD

**Issue by ArighnaIITG** [sympy/planet-sympy#96]
I have been posting all my GSoC blogs here at this [link](https://arighna.github.io). The `url` in the `config.yml` file of my github.io repository was wrongly updated previously. I have updated it correctly, but the link still seems to be broken.
What can be done in this case? Can I remove the link from `planet-sympy`, and re-host it again? Any suggestions? @asmeurer @certik

**Comment by certik** [comment]
The computer that used to trigger the pipeline using cron was turned down by me (I forgot that it was doing it). I just fixed it by triggering the pipeline periodically from the GitLab gui. So things should work from now on.

**Comment by ArighnaIITG** [comment]
Thanks @certik . Issue has been resolved. Closing it.

**Comment by certik** [comment]
I set the pipelines [here](https://gitlab.com/sympy/planet-sympy-updater/pipelines) to trigger every 20 minutes, but I think GitLab only triggers every half an hour as the most frequent interval, which is fine. Now it runs completely at GitLab, automatically, does not require an external computer triggering the pipeline. So it should work from now on.
